require("plugins-setup")

require("core.options")
require("core.keymaps")
require("core.colorscheme")

--plugins configuirations
require("plugins.nvim-tree")
require("plugins.indent-blankline")
require("plugins.lualine")
require("plugins.bufferline")
require("plugins.telescope")
require("plugins.nvim-cmp")
require("plugins.lsp.mason")
require("plugins.lsp.lspsaga")
require("plugins.lsp.lspconfig_saga")
require("plugins.comment")
require("plugins.todo-comments")
require("plugins.sorround")
require("plugins.symbols-outline")
require("plugins.autopairs")
require("plugins.treesitter")
require("plugins.gitsigns")
require("plugins.which-key")
